AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bastion Host Deployment'

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC

  InstanceSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select the subnet for the bastion host

  EC2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the EC2 Key Pair to use for instance

  PublicIP:
    Type: String
    Description: Public IP address from which to restrict traffic from (e.g., 12.34.56.78/32)
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: '41.234.201.104/32'
    ConstraintDescription: Value must be in the format of <ip address>/<cidr>

  UnderlyingOS:
    Type: String
    Description: Select the desired operating system.
    AllowedValues:
      - Linux
      - Windows
  InstanceSize:
    Type: String
    Description: Select an instance size
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
 
Mappings:

  Windows:
    us-east-1:
      "AMI": "ami-603b1c1a"
    us-east-2:
      "AMI": "ami-16370073"
    us-west-1:
      "AMI": "ami-e8b6be88"
    us-west-2:
      "AMI": "ami-74800e0c"

  Linux:
    us-east-1:
      "AMI": "ami-1853ac65"
    us-east-2:
      "AMI": "ami-25615740"
    us-west-1:
      "AMI": "ami-bf5540df"
    us-west-2:
      "AMI": "ami-d874e0a0"

Conditions:

  IsItWindows: !Equals [!Ref UnderlyingOS, "Windows"]
  IsItLinux: !Equals [!Ref UnderlyingOS, "Linux"]

Resources:

  WindowsBastionHost:
    Type: AWS::EC2::Instance
    Condition: IsItWindows
    DependsOn:
      - WindowsRDPSecurityGroup
    Properties:
      ImageId: !FindInMap [Windows, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceSize
      KeyName: !Ref EC2KeyPair
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: WindowsRDPSecurityGroup
          SubnetId:
            Ref: InstanceSubnet
      Tags:
      - Key: "Name"
        Value: "Windows Bastion"
      - Key: "Environment"
        Value: "Management"
      - Key: "Operating System"
        Value: "Windows Server"

  WindowsRDPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: IsItWindows
    Properties:
      GroupDescription: Allows port inbound for RDP
      GroupName: windows-bastion-rdp
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3389'
        ToPort: '3389'
        CidrIp: !Ref PublicIP

  LinuxBastionHost:
    Type: AWS::EC2::Instance
    Condition: IsItLinux
    DependsOn:
      - LinuxSSHSecurityGroup
    Properties:
      ImageId: !FindInMap [Linux, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceSize
      KeyName: !Ref EC2KeyPair
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: LinuxSSHSecurityGroup
          SubnetId:
            Ref: InstanceSubnet
      Tags:
      - Key: "Name"
        Value: "Linux Bastion"
      - Key: "Environment"
        Value: "Management"
      - Key: "Operating System"
        Value: "Amazon Linux"
      UserData:
          'Fn::Base64': 
             !Sub |
               #!/bin/bash
               yum update -y
               sed -i 's/#Port 22/Port 19991/g' /etc/ssh/sshd_config
               service sshd restart               

  LinuxSSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: IsItLinux
    Properties:
      GroupDescription: Allows port inbound for SSH
      GroupName: linux-bastion-ssh
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '19991'
        ToPort: '19991'
        CidrIp: !Ref PublicIP
Outputs:
  ExternalUrl:
    Description: SSH IP
    Value: !Sub ec2-user@${LinuxBastionHost.PublicIp}
    Export:
      Name: SSH-IP